### ISSUE TITLE
XML syntax check and OSIS validation

### ISSUE THREAD

**Issue by DavidHaslam** [lemtom/Canisius#1]
Currently the XML fails syntax check. That needs fixing.

Then in order to validate the OSIS to the remote schema, please replace line 1 with

<?xml version="1.0" encoding="utf-8"?>
<osis xmlns="http://www.bibletechnologies.net/2003/OSIS/namespace"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.bibletechnologies.net/2003/OSIS/namespace
        http://www.bibletechnologies.net/osisCore.2.1.1.xsd">

**Comment by DavidHaslam** [comment]
See http://www.crosswire.org/wiki/OSIS_Bibles#Tools

**Comment by DavidHaslam** [comment]
btw. Although I'm a member of the modules list, I don't participate in the IRC for CrossWire.

**Comment by lemtom** [comment]
Okay, I shall see if I can get the XML corrected. I now recall having to do that for the Catena module as well. It's been a while.

**Comment by lemtom** [comment]
Okay, I have corrected all the issues the XMl validators gave me, except that it still complains about the closing tag </osisText>, but I can't seem to fix that.

**Comment by DavidHaslam** [comment]
Which XML Editor do you use?

I general use Notepad++ together with the XML Tools Plugin.

This editor has a powerful search feature. I've been using it for years.

**Comment by DavidHaslam** [comment]
You have three missing &lt;/div> elements.

There are 75 &lt;div...> but only 72 &lt;/div>

XML Syntax Check still fails. This doesn't depend on the file being OSIS.

This has to pass before one performs the OSIS validation testing.

**Comment by DavidHaslam** [comment]
I've got the file to pass XML syntax check. There are now 74 of each.
There are 73 book divisions and Daniel has a section division.

I've not forked, so I'll email you the correction.

**Comment by lemtom** [comment]
Ah, I think I have corrected it on my end too.

**Comment by lemtom** [comment]
some divs that should have been /divs

**Comment by DavidHaslam** [comment]
To write any XML elements in a comment here, replace the opening "<" by "& l t ;" without the spaces.

Preview first to check.

**Comment by lemtom** [comment]
Well, I think you understood what I meant in any case.

Anyway, to rephrase it, the issue in my XML validator concerned &lt;div> tags which should have been &lt;/div> tags. I also made some significant changes to the footnotes, after a conversation with Peter von Kaehne.

**Comment by DavidHaslam** [comment]
XML now validates to OSIS. Closing issue.
